spring:
  datasource:
    password: 52435000l.AG
    username: root
    url: jdbc:mysql://192.168.234.129:3306/student_management?serverTimezone=GMT%2B8&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
mybatis:
  config-location: classpath:/mybatis/mybatis_config.xml
  mapper-locations: classpath:/mybatis/mapper/*.xml
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
#logging:
#  level:
#   com.liu.mapper: debug